### ISSUE TITLE
creating-json-apis-with-onyx-part-2: undefined method 'content='

### ISSUE THREAD

**Issue by shanlalit** [onyxframework/blog#1]
Hi,

I'm new to Crystal but not to Ruby :).

I was following your tutorial -- it seems - there is some issue with the "changeset" it gives an error on

`
    if content = params.json.content
      changeset.content = content
    end
`

Error:

`
undefined method 'content=' for Onyx::SQL::Model::Changeset(Models::Item, Bool | Int32 | String | Time | Nil) Scry
`

It works with the example as mentioned in the code.

`
    changeset = item.changeset

    unless params.json.completed.nil?
      changeset.update(completed: params.json.completed)
    end
`
What's the correct way, please update the blog post accordingly.

Thanks for sharing Onyx with us.

**Comment by shanlalit** [comment]
One more thing after update the updatedAt remains null is that a bug?

**Comment by vladfaust** [comment]
Thank you very much for your report, Lalit @shanlalit! Yeah, it was a *blog bug*, for some reason I forgot to update the lines... I've fixed it!

BTW, if you have a question rather than bug report, don't hesitate to chat at https://gitter.im/onyxframework/Lobby :+1:

**Comment by shanlalit** [comment]
Thank you very much for quick reply and addressing the issue.

I will surely ping in the Gitter Lobby; if needed.
